[package]
name = "openapi"
version = "4.0.1-pre.0"
authors = ["blah@cliffano.com"]
description = "OpenAPI client for ipify, a simple public IP address API"
license = "MIT"
edition = "2018"

[dependencies]
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
url = "^2.2"
uuid = { version = "^1.0", features = ["serde"] }
[dependencies.reqwest]
version = "^0.11"
features = ["json", "multipart"]
