openapi: 3.0.0
info:
  version: 5.0.0
  title: openapi-ipify
  description: OpenAPI client for ipify, a simple public IP address API
  license:
    name: MIT
  contact:
    name: Cliffano Subagio
    url: http://blog.cliffano.com
    email: blah@cliffano.com
servers:
  - url: https://api.ipify.org
paths:
  /:
    get:
      summary: Get your public IP address
      operationId: getIp
      parameters:
        - name: format
          in: query
          description: Response format
          required: false
          schema:
            type: string
            enum:
              - json
              - jsonp
        - name: callback
          in: query
          description: JSONP callback function name
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Your public IP address
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ip'
            application/javascript:
              schema:
                type: string
            text/plain:
              schema:
                type: string
components:
  schemas:
    Ip:
      required:
        - ip
      properties:
        ip:
          type: string
