name: Publish JavaScript
'on':
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
        with:
          ref: main
      - uses: ./.github/actions/publish-javascript-action
        env:
          NPMJS_TOKEN: ${{ secrets.NPMJS_TOKEN }}
