name: Publish Python-nextgen
'on':
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: 4.0.0
      - uses: ./.github/actions/publish-python-nextgen-action
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
